apply plugin: 'com.android.library'

android {
    namespace 'io.noties.markwon.html'

    compileSdkVersion 35
    buildToolsVersion '35.0.0'

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName version
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    
    buildTypes {
        debug {
            minifyEnabled false
        }
        
        release {
            minifyEnabled false
        }
        
        standalone {
            minifyEnabled false
        }
    }
}

repositories {
    mavenCentral()
    google()
}

dependencies {

    api project(':markwon-core')
    compileOnly 'com.atlassian.commonmark:commonmark-ext-gfm-strikethrough:0.13.0'
//
//    deps.with {
        // add a compileOnly dependency, so if this artifact is present
        // we will try to obtain a SpanFactory for a Strikethrough node and use
        // it to be consistent with markdown (please note that we do not use markwon plugin
        // for that in case if different implementation is used)
//        compileOnly it['commonmark-strikethrough']
//
//        testImplementation it['ix-java']
//    }
//
//    deps.test.with {
//        testImplementation it['junit']
//        testImplementation it['robolectric']
//    }
}

//registerArtifact(this)
