apply plugin: 'com.android.library'

android {
    namespace 'io.noties.markwon.ext.strikethrough'

    compileSdkVersion 35
    buildToolsVersion '35.0.0'

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName version
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    
    buildTypes {
        debug {
            minifyEnabled false
        }
        
        release {
            minifyEnabled false
        }
        
        standalone {
            minifyEnabled false
        }
    }
}

repositories {
    mavenCentral()
    google()
}

dependencies {

    api project(':markwon-core')
    api 'com.atlassian.commonmark:commonmark-ext-gfm-strikethrough:0.13.0'

//    deps.with {
//        api it['commonmark-strikethrough']

        // NB! ix-java dependency to be used in tests
//        testImplementation it['ix-java']
    }

//    deps.test.with {
//        testImplementation project(':markwon-test-span')
//        testImplementation it['junit']
//        testImplementation it['mockito']
//        testImplementation it['robolectric']
//    }
//}

//registerArtifact(this)